Lan = "EN"
"起手爆发药" = "OpenerPotion"
"停手" = "Stop"
"爆发" = "Burst"
"最终爆发" = "FinalBurst"
"机器人" = "Battery"
"野火优先" = "Wildfire First"
"过热前高威力技能检查时间" = "Determine the minimum cooldown for strongGcd when using HyperCharge (ms)"
"自动攻击" = "Pull"
"机工电量轴 (起手不算)" = "BatteryList (Ignore opener)"
"过热" = "HyperCharge"