Lan = "EN"
"爆发药(仅起手)" = "OpenerPotion"
"最终爆发" = "FinalBurst"
"灼热之光" = "SearingLight"
"自动火神冲" = "AutoCrimsonCyclone"
"当前三神顺序：" = "Current Summon order:"
"土神优先" = "Titan First"
"火神优先" = "Ifirt First"
"风神优先" = "Garuda First"
"巴哈凤凰" = "BahamutPhoenix"
"三神召唤" = "Summon"
"土神" = "Titan"
"火神" = "Ifirt"
"风神" = "Garuda"
"即刻咏唱模式：" = "SwiftCast Mode:"
"即刻复活" = "SwiftCast→Resurrection"
"风神读条" = "SwiftCast→Slipstream"
"火神读条" = "SwiftCast→RubyRite"
"SMN/巴哈凤凰开关" = "SMN/Switch BahamutPhoenix"
"SMN/下一轮三神技能使用次数" = "SMN/Number of action in next three primal phases"
"SMN/灼热之光开关" = "SMN/Switch SearingLight"
"SMN/选择下一个召唤的蛮神" = "SMN/Choose the next primal phases to use"
"SMN/三神召唤开关" = "SMN/Switch Summon"